export const dummySuggestions = [
  { id: 1, title: "Tree Plantation", description: "The U.S. Bureau of Reclamation has taken a monumental step in enhancing the safety of California's water infrastructure by awarding a $255 million contract to NW Construction for Phase 2 of the B.F. Sisk Dam Safety of Dams Modification Project. Located on the west side of the San Joaquin Valley, the B.F. Sisk Dam plays a crucial role in California's complex water delivery system. This recent development is not only a significant investment in public safety but also a forward-thinking move to secure water reliability for millions of Californians.\n\nBuilt in 1967, the B.F. Sisk Dam impounds the San Luis Reservoir, the largest offstream reservoir in the United States. Unlike traditional reservoirs, it does not have its own watershed but instead stores water diverted from the Sacramento-San Joaquin Delta. This reservoir supports water deliveries across Silicon Valley, San Joaquin Valley, the Central Coast, and Southern California. The importance of this structure cannot be overstated -- it serves agricultural lands, urban areas, and even wildlife refuges.\n\nThe dam's location in a known seismic zone near the Ortigalita Fault adds complexity and urgency to the safety enhancements. Under the 1978 Safety of Dams Act, the Reclamation's Dam Safety Program has prioritized this site due to the identified risks.\n\nThe newly awarded contract for Phase 2 focuses on constructing a massive stability berm along the central section of the 3.5-mile-long dam. This berm will use approximately 15 million cubic yards of earthen material, reinforcing the structure against seismic threats. Additionally, the final stages will see the dam's crest raised by 10 feet. These actions are designed to prevent catastrophic failure through slumping or overtopping during an earthquake.\n\nPhase 1, completed in 2024, included foundational preparations and the beginning of berm construction. With Phase 2, the project moves into full-scale structural enhancements that are crucial for the safety and reliability of California's water supply.\n\nAccording to Acting Regional Director Adam Nickels, \"This project represents a major investment in the future of California's water supply and the communities and ecosystems that depend on it.\" The financial and structural commitments reflect California's proactive stance on water management amid increasing climate variability and growing population needs.\n\nThese modifications also have ripple effects -- improved infrastructure supports economic stability, especially in the agriculture-dominated Central Valley. Enhanced dam integrity translates into more dependable water access for farmers, municipalities, and industries" },
  { id: 2, title: "Tech Fest 2025", description: "Annual intercollege tech event." }
];

// Dummy API
export const postNewsStory = (data) => {
  console.log("Posting News & Story:", data);
  return Promise.resolve({ success: true });
};

export const postEvent = (data) => {
  console.log("Posting Event:", data);
  return Promise.resolve({ success: true });
};